CUTFLI/ViewModels/Barbers.cs
namespace CUTFLI.ViewModels
{
    public class Barbers
    {
        public int? Id { get; set; }
        public string FullName { get; set; }
        public byte[] Image { get; set; }
    }
}

CUTFLI/Controllers/CutFliController.cs
using AutoMapper;
using CUTFLI.Enums;
using CUTFLI.Models;
using CUTFLI.ViewModels;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MimeKit;
using NToastNotify;
using System.Collections.Generic;
using System.Globalization;
using static CUTFLI.Enums.SystemEnums;
using SmtpClient = MailKit.Net.Smtp.SmtpClient;

namespace CUTFLI.Controllers
{
    public class CutFliController : Controller
    {
        private readonly CUTFLIDbContext _dbContext;
        private readonly IToastNotification _toastNotification;
        private readonly IMapper _mapper;
        private readonly IConfiguration _configuration;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly ILogger<CutFliController> _logger;
        public CutFliController(CUTFLIDbContext dbContext,
            IToastNotification toastNotification,
            IMapper mapper,
            IConfiguration configuration,
            IWebHostEnvironment webHostEnvironment,
            ILogger<CutFliController> logger
            )
        {
            _dbContext = dbContext;
            _toastNotification = toastNotification;
            _mapper = mapper;
            _configuration = configuration;
            _webHostEnvironment = webHostEnvironment;
            _logger = logger;
        }


        public IActionResult GetVideo(string videoName)
        {
            try
            {
                _logger.LogInformation($"CutFliController-GetVideo videoName={videoName}");
                string folderName = "Videos\\" + videoName;
                var filePath = Path.Combine(_webHostEnvironment.WebRootPath, folderName);
                byte[] b = System.IO.File.ReadAllBytes(filePath);
                return File(b, "video/mp4");
            }
            catch (Exception ex)
            {
                _logger.LogError(ex, "CutFliController-GetVideo exception :");
                return NotFound();
            }
        }
        public async Task<IActionResult> Index()
        {
            try
            {
                _logger.LogDebug($"CutFliController-Index");
                var videoName = await _dbContext.Videos.FirstOrDefaultAsync();
                if (videoName != null)
                {
                    ViewBag.Video = videoName.VideoName;
                }
                else
                {
                    ViewBag.Video = "cutflix.MP4";
                }
                var employees = await _dbContext.Users.Where(x => x.Permission != SystemEnums.Permission.Admin).Skip(0).Take(4).ToListAsync();
                var model = _mapper.Map<List<User>, List<Barbers>>(employees);
                return View(model);
            }
            catch (Exception ex)
            {
                _toastNotification.AddErrorToastMessage("Error Found");
                _logger.LogError(ex, "CutFliController-Index exception :");
                return View(new List<Barbers>());
            }
        }
        public async Task<IActionResult> Appointments(int? service, DateTime? date)
        {
            try
            {
                _logger.LogDebug($"CutFliController-Appointments service={service} date={date}");
                DateTime startDate = DateTime.Now;
                DateTime endDate = startDate.AddDays(4);

                if (service != null)
                {
                    var serviceDb = await _dbContext.Services.FirstOrDefaultAsync(x => x.Id == (int)service);
                    if (serviceDb != null)
                    {
                        HttpContext.Session.SetInt32("serviceId", (int)service);
                        HttpContext.Session.SetString("service", serviceDb.Name);
                        HttpContext.Session.SetString("servicePrice", serviceDb.Price.ToString());
                    }
                }
                ViewData["minValue"] = DateTime.Now.ToString("yyyy-MM-dd");
                if (date != null)
                {
                    if (date.Value.Date < DateTime.Now.Date)
                    {
                        _toastNotification.AddErrorToastMessage("Wrong date");
                        return View(new List<CustomerAppointments>());
                    }
                    ViewData["value"] = date?.ToString("yyyy-MM-dd");

                    startDate = (DateTime)date;
                    endDate = startDate.AddDays(4);
                }

                int barber = (int)HttpContext.Session.GetInt32("barberId");

                var appointments = await _dbContext.Appointments.Where(x => x.UserId == barber
                && x.Status == SystemEnums.AppointmentStatus.Available
                && x.Date.Date >= startDate.Date && x.Date.Date <= endDate.Date)
                    .Include(x => x.User)
                    .GroupBy(x => x.Date)
                    .Select(x =>
                new DateAppointments
                {
                    StartDate = startDate,
                    DayName = x.Key.ToString("dddd", CultureInfo.InvariantCulture),
                    DayNumber = x.Key.ToString("MMMM d") + GetDaySuffix(x.Key.Day),
                    Appointments = x.Select(x =>
                    new StartTimeViewModel
                    {
                        Id = x.Id,
                        StartTime = x.StartTime
                    }).ToList()
                }).ToListAsync();

                if (!appointments.Any())
                {
                    appointments = new List<DateAppointments>();
                    for (DateTime dateLoop = startDate; dateLoop <= endDate; dateLoop = dateLoop.AddDays(1))
                    {
                        appointments.Add(new DateAppointments
                        {
                            StartDate = startDate,
                            DayName = dateLoop.ToString("dddd", CultureInfo.InvariantCulture),
                            DayNumber = dateLoop.ToString("MMMM d") + GetDaySuffix(dateLoop.Day),
                            Appointments = new List<StartTimeViewModel>(),
                        });
                    }
                }

                var response = new BookAppointments() { };
                response.CustomerAppointments = new AppointmentsWithDate
                {
                    StartDate = startDate,
                    Appointments = appointments,
                };
                response.People = new PeopleViewModel();


                return View(response);
            }
            catch (Exception ex)
            {
                _toastNotification.AddErrorToastMessage("Error Found");
                _logger.LogError(ex, "CutFliController-Appointments exception :");
                return RedirectToAction(nameof(Index));
            }
        }

        public async Task<IActionResult> GetAppointmentsByDate(string date)
        {
            try
            {
                _logger.LogDebug($"CutFliController-GetAppointmentsByDate date={date}");
                DateTime startDate = Convert.ToDateTime(date);
                DateTime endDate = startDate.AddDays(4);

                int? barber = (int)HttpContext.Session.GetInt32("barberId");

                if (startDate.Date < DateTime.Now.Date)
                {
                    startDate = DateTime.Now;
                    endDate = startDate.AddDays(4);
                }

                var appointments = await _dbContext.Appointments.Where(x => x.UserId == barber
                && x.Status == SystemEnums.AppointmentStatus.Available
                && x.Date.Date >= startDate.Date && x.Date.Date <= endDate.Date)
                    .Include(x => x.User)
                    .GroupBy(x => x.Date)
                    .Select(x =>
                new DateAppointments
                {
                    StartDate = startDate,
                    DayName = x.Key.ToString("dddd", CultureInfo.InvariantCulture),
                    DayNumber = x.Key.ToString("MMMM d") + GetDaySuffix(x.Key.Day),
                    Appointments = x.Select(x =>
                    new StartTimeViewModel
                    {
                        Id = x.Id,
                        StartTime = x.StartTime
                    }).ToList()
                }).ToListAsync();

                if (!appointments.Any())
                {
                    appointments = new List<DateAppointments>();
                    for (DateTime dateLoop = startDate; dateLoop <= endDate; dateLoop = dateLoop.AddDays(1))
                    {
                        appointments.Add(new DateAppointments
                        {
                            StartDate = startDate,
                            DayName = dateLoop.ToString("dddd", CultureInfo.InvariantCulture),
                            DayNumber = dateLoop.ToString("MMMM d") + GetDaySuffix(dateLoop.Day),
                            Appointments = new List<StartTimeViewModel>(),
                        });
                    }
                }

                var result = new AppointmentsWithDate();
                result.StartDate = startDate;
                result.Appointments = appointments;

                return PartialView("_Appointments", result);
            }
            catch (Exception ex)
            {
                _toastNotification.AddErrorToastMessage("Error Found");
                _logger.LogError(ex, "CutFliController-GetAppointmentsByDate exception :");
                return PartialView("_Appointments", new List<CustomerAppointments>());
            }
        }
        public async Task<IActionResult> Barbers()
        {
            try
            {
                _logger.LogDebug($"CutFliController-Barbers");
                var employees = await _dbContext.Users.Where(x => x.Permission != SystemEnums.Permission.Admin).ToListAsync();
                if (employees != null)
                {
                    var model = _mapper.Map<List<User>, List<Barbers>>(employees);

CUTFLI/Controllers/ServicesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using CUTFLI.Models;
using CUTFLI.ViewModels;
using AutoMapper;
using System.Security.Claims;
using NToastNotify;
using Microsoft.AspNetCore.Authorization;

namespace CUTFLI.Controllers
{
    [Authorize]
    public class ServicesController : Controller
    {
        private List<string> allowedExtensions = new List<string>() { ".png", ".jpg" };
        private readonly CUTFLIDbContext _context;
        private readonly IMapper _mapper;
        private readonly IToastNotification _toastNotification;

        public ServicesController(CUTFLIDbContext context, IMapper mapper, IToastNotification toastNotification)
        {
            _context = context;
            _mapper = mapper;
            _toastNotification = toastNotification;
        }

        public async Task<IActionResult> Index()
        {
            try
            {
                var services = await _context.Services.OrderByDescending(x => x.CreatedDate).ToListAsync();
                var model = _mapper.Map<List<Service>, List<ServiceViewModel>>(services);
                return View(model);
            }
            catch (Exception)
            {
                _toastNotification.AddErrorToastMessage("Error Found");
                return RedirectToAction(nameof(Index));
            }
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ServiceViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    int? currentUserId = Convert.ToInt32(HttpContext.User.FindFirstValue(ClaimTypes.NameIdentifier));
                    var files = Request.Form.Files;
                    using var stream = new MemoryStream();
                    if (files.Any())
                    {
                        var image = files.FirstOrDefault();
                        if (allowedExtensions.Contains(Path.GetExtension(image.FileName).ToLower()))
                        {
                            if (image.Length < 3145728) // 3 MB
                            {
                                await image.CopyToAsync(stream);
                            }
                            else
                            {
                                ModelState.AddModelError("Image", "Image can't be larger than 3 MB");
                                return View(model);
                            }
                        }
                    }
                    else
                    {
                        ModelState.AddModelError("Image", "Image required");
                        return View(model);
                    }
                    var service = _mapper.Map<ServiceViewModel, Service>(model);
                    service.CreatedDate = DateTime.Now;
                    service.CreatedBy = currentUserId;
                    service.Image = files.Any() ? stream.ToArray() : null;
                    await _context.AddAsync(service);
                    await _context.SaveChangesAsync();
                    _toastNotification.AddSuccessToastMessage("Service Added successfully");
                    return RedirectToAction(nameof(Index));
                }
                return View(model);
            }
            catch (Exception)
            {
                _toastNotification.AddErrorToastMessage("Error Found");
                return RedirectToAction(nameof(Index));
            }
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Services == null)
            {
                return NotFound();
            }

            var service = await _context.Services.FindAsync(id);
            if (service == null)
            {
                return NotFound();
            }
            var model = _mapper.Map<Service, ServiceViewModel>(service);
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ServiceViewModel model)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var files = Request.Form.Files;
                    using var stream = new MemoryStream();
                    if (files.Any())
                    {
                        var image = files.FirstOrDefault();
                        if (allowedExtensions.Contains(Path.GetExtension(image.FileName).ToLower()))
                        {
                            if (image.Length < 3145728) // 3 MB
                            {
                                await image.CopyToAsync(stream);
                            }
                            else
                            {
                                ModelState.AddModelError("Image", "Image can't be larger than 3 MB");
                                return View(model);
                            }
                        }
                    }
                    var service = await _context.Services.FindAsync(model.Id);
                    if (service != null)
                    {
                        if (_context.Services.Where(x => x.Name.ToLower() == model.Name.ToLower() && x.Id != model.Id).Any())
                        {
                            ModelState.AddModelError("Name", "Service exist");
                            return View(model);
                        }
                        service.Name = model.Name;
                        service.Price = model.Price;
                        service.Description = model.Description;
                        service.Gender = model.Gender;
                        service.Image = files.Any() ? stream.ToArray() : service.Image;
                        _context.Update(service);
                        await _context.SaveChangesAsync();
                    }
                    return RedirectToAction(nameof(Index));
                }
                return View(model);
            }
            catch (Exception)
            {
                _toastNotification.AddErrorToastMessage("Error Found");
                return RedirectToAction(nameof(Index));
            }

        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Services == null)
            {
                return NotFound();
            }

            var service = await _context.Services.FindAsync(id);
            if (service == null)
            {
                return NotFound();
            }
            var serviceModel = _mapper.Map<ServiceViewModel>(service);
            return View(serviceModel);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Services == null)
            {
                return Problem("Entity set 'CUTFLIDbContext.Services'  is null.");
            }
            var service = await _context.Services.FindAsync(id);
            if (service != null)
            {
                _context.Services.Remove(service);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ServiceExists(int id)
        {
            return _context.Services.Any(e => e.Id == id);
        }
    }
}

CUTFLI/Views/CutFli/Barbers.cshtml
@model IEnumerable<CUTFLI.ViewModels.Barbers>

@{
    Layout = "~/Views/Shared/_UiLayout.cshtml";
}

<div class="bg-image position-relative">
    <img src="~/assets/img/Ui/Frame0.png" class="w-100 img-fluid" />
    <div class="overlay2"></div>
    <div class="mask2 text-light d-flex justify-content-center align-items-center">
        <h1 class="fw-bolder">Barbers</h1>
    </div>
</div>

<div class="d-flex justify-content-center">
    <img src="~/assets/img/Ui/2 2.png" alt="" class="imglogo">
</div>


<div class="" id="barbers">
    <div class="d-flex justify-content-center">
        <p class=" text text-center"> Barbers</p>

    </div>
    <div class="d-flex justify-content-center">
        <p class="align-content-center text-center col-md-5 col-11">
            Lorem ipsum dolor sit amet, consectetur adipiscing
            elit. Ut elit tellus, luctus nec ullamcorper
            mattis, pulvinar dapibus leo.
        </p>
    </div>
    <div class="container-fluid py-5">
        <div class=" flex-wrap d-flex p-lg-5">
           @foreach (var item in Model)
           {
                <div class="col-6 col-md-4 p-3 barber">
                    <a asp-controller="CutFli" asp-action="Services" asp-route-barber="@item.Id">
                        <div class="bg-image w-100 position-relative">
                            <img src="@("data:image/*;base64,"+Convert.ToBase64String(item.Image))" class="w-100 homeimg img-fluid" style="height: 750px;" />
                            <div class="overlayy"></div>
                            <div class="maskk text-light d-flex justify-content-center align-items-center">
                                <h2 class="px-2 mb-auto" id="text">@item.FullName</h2>
                            </div>
                        </div>
                    </a>
                </div>
            }
        </div>
    </div>
</div>



@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

CUTFLI/Views/CutFli/Book.cshtml
@model CUTFLI.ViewModels.PeopleViewModel

<div id="bookingFormContainer">
    <form method="POST" asp-controller="CutFli" asp-action="Book" class="py-4 " id="bookingForm">
        <input type="hidden" asp-for="AppointmentId" id="AppointmentId" name="AppointmentId" />
        <div class="form-group">
            <input asp-for="FullName" type="text" class="form-control form-control-lg border border-2" id="Name"
                   placeholder="Your Name" style="background-color: black;">
        </div>
        <div class="row pt-3">
            <div class="col-md-6 mt-sm-3">
                <input asp-for="PhoneNumber" type="text" class="form-control form-control-lg border border-2"
                       placeholder="Your PhoneNumber" style="background-color: black;">
            </div>
            <br>
            <div class="col-md-6 pt-2">
                <input asp-for="Email" type="email" class="form-control border border-2 form-control-lg mt-sm-2"
                       placeholder="Your E-mail" style="background-color: black; color: #fff;">
            </div>
        </div>
        <div class="form-group pt-3">
            <textarea asp-for="Message" class="form-control border border-2" id="exampleFormControlTextarea1"
                      placeholder="Your Message" rows="6" style="background-color: black;"></textarea>
        </div>
        <div class="text-center pt-3">
            <button style="border: #fff 2px solid;" type="submit" class="btn px-5">
                <h4 class="text-capitalize px-5">Book</h4>
            </button>
        </div>
    </form>
</div>

@section Scripts {
        $('#bookingForm').submit(function (e) {
            e.preventDefault();

            var formData = $(this).serialize();

            $.ajax({
                url: $(this).attr('action'),
                type: $(this).attr('method'),
                data: formData,
                success: function (result) {
                    $('#bookingFormContainer').html(result)
                },
            });
        });
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");


    }
    }
    

CUTFLI/Views/CutFli/EmployeeAppointments.cshtml
@using CUTFLI.Enums
@model CUTFLI.ViewModels.EmployeeDetails

@{
    Layout = "~/Views/Shared/_UiLayout.cshtml";
}
<div class="row d-flex justify-content-center mb-5">
    <div class="my-5">
        <h1 class="display-6 text-center" style="color:#9E8D5D !important;"><span id="ourText">Appointments</span></h1>
    </div>
    <div class="mb-5">
        <form asp-action="EmployeeAppointments" class="d-flex justify-content-center gap-3">
            <input type="hidden" name="employee" value="@Model.Id" />
            <input type="date" value="@ViewData["value"]" min="@ViewData["minValue"]" class="me-3 text-dark appointmentDate" name="date">
            <button type="submit" class="btn">Search</button>
        </form>
    </div>
    <div class="table-responsive col-12 col-md-6 px-4">
        <table class="table text-center">
            <thead>
                <tr>
                    <th>Start</th>
                    <th>End</th>
                    <th>Employee</th>
                    <th>Status</th>
                    <th>Action</th>
                </tr>
            </thead>
            @foreach (var item in Model.CustomerAppointments)
            {
                <tr>
                    <td style="color: #9E8D5D !important;">@(new DateTime(item.StartTime.Ticks).ToString("hh:mm tt"))</td>
                    <td style="color: #9E8D5D !important;">@(new DateTime(item.EndTime.Ticks).ToString("hh:mm tt"))</td>
                    <td style="color: #9E8D5D !important;">@(item.User.FullName)</td>
                    <td style="color: #9E8D5D !important;">@(item.Status)</td>
                    <td>
                        @if (item.Status == SystemEnums.AppointmentStatus.Available)
                        {
                            <a asp-action="Book" asp-route-appointmentId="@item.Id" class="btn">Book</a>
                        }
                        else
                        {
                            <p class="text-danger">Booked</p>
                        }
                    </td>
                </tr>
            }
        </table>
    </div>
</div>




@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

CUTFLI/Views/CutFli/Index.cshtml
@model IEnumerable<CUTFLI.ViewModels.Barbers>
@{
    Layout = "~/Views/Shared/_UiLayout.cshtml";
}
<div class="play" style="position: relative;">
    <video id="myVideo" class="img-fluid h-100 w-100" poster="~/assets/img/ui/poster.png" playsinline>
        <source id="mp4_src" src="@Url.Action("GetVideo","CutFli", new { videoName = ViewBag.Video })" type="video/mp4">
        Your browser does not support the video tag.
    </video>
    <svg id="playButton" xmlns="http://www.w3.org/2000/svg" width="150" height="150" viewBox="0 0 35 34" fill="none" style="position: absolute; top: 50%; left: 50%; transform: translate(-50%, -50%);">
        <path fill-rule="evenodd" clip-rule="evenodd" d="M17.5 31.884C25.7519 31.884 32.4414 25.2204 32.4414 17.0001C32.4414 8.77992 25.7521 2.11613 17.5 2.11613C9.2481 2.11613 2.55856 8.77992 2.55856 17.0001C2.55856 25.2202 9.2481 31.884 17.5 31.884ZM17.5 33.5377C26.6687 33.5377 34.1016 26.1334 34.1016 17.0001C34.1016 7.8665 26.6687 0.462402 17.5 0.462402C8.33114 0.462402 0.898438 7.8665 0.898438 17.0001C0.898438 26.1334 8.33114 33.5377 17.5 33.5377Z" fill="white" />
        <path fill-rule="evenodd" clip-rule="evenodd" d="M21.8142 17.0003L14.1798 11.9303V22.0704L21.8142 17.0003ZM23.3566 16.0371C24.0467 16.4954 24.0467 17.5053 23.3566 17.9636L14.3263 23.9607C13.554 24.4736 12.5195 23.922 12.5195 22.9974V11.0033C12.5195 10.0787 13.554 9.52724 14.3263 10.0401L23.3566 16.0371Z" fill="white" />
    </svg>
</div>


<div class="d-flex justify-content-center">
    <img src="~/assets/img/Ui/2 2.png" alt="" class="imglogo">
</div>
<div class="d-flex justify-content-center">
    <p class=" text text-center"> Barbers</p>

</div>
<div class="d-flex justify-content-center">
    <p class="align-content-center col-md-5 col-11 text-center">
        Lorem ipsum dolor sit amet, consectetur adipiscing
        elit. Ut elit tellus, luctus nec ullamcorper
        mattis, pulvinar dapibus leo.
    </p>
</div>




<div class="p-md-5 m-md-4">
    <div class=" position-relative">
        <div class="d-flex flex-wrap p-2">
            @foreach (var item in Model)
            {
                <div class="col-6 p-3 ">
                  @*  <div class="w-100 position-relative">
                        <a asp-controller="CutFli" asp-action="Services" asp-route-barber="@item.Id">
                            <img src="@("data:image/*;base64,"+Convert.ToBase64String(item.Image))" alt="" class="w-100 p-3 homeimg" style="height: 750px;">
                    </a>
                        <div class="overlayy"></div>

                        <div class="maskk text-light d-flex justify-content-center align-items-center">
                            <h3 class="text-center text-uppercase py-4">@item.FullName</h3>
                        </div>
                </div>*@
                    <a asp-controller="CutFli" asp-action="Services" asp-route-barber="@item.Id">
                        <div class="bg-image w-100 position-relative">
                            <img src="@("data:image/*;base64,"+Convert.ToBase64String(item.Image))" class="w-100 homeimg img-fluid" style="height: 750px;" />
                            <div class="overlayy"></div>
                            <div class="maskk text-light d-flex justify-content-center align-items-center">
                                <h2 class="text-center mb-auto text-uppercase" id="text">@item.FullName</h2>
                            </div>
                        </div>
                    </a>
                  
            </div>
            }

        </div>
    </div>
</div>

<script src="~/js/index.js"></script>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }

CUTFLI/Views/CutFli/Services.cshtml
@model IEnumerable<CUTFLI.ViewModels.UserServiceViewModel>
@{
    Layout = "~/Views/Shared/_UiLayout.cshtml";
}
<div class="bg-image position-relative">
    <img src="~/assets/img/Ui/Frame0.png" class="w-100 img-fluid" />
    <div class="overlay2"></div>
    <div class="mask2 text-light d-flex justify-content-center align-items-center">
        <h1 class="fw-bolder">Services</h1>
    </div>
</div>

<div class="d-flex justify-content-center">
    <img src="~/assets/img/Ui/2 2.png" alt="" class="imglogo">
</div>

<div class="container" id="service">
    <div class="text-center">
        <p class=" text text-center"> @Context.Session.GetString("barber") Services </p>
    </div>
    <div class="row py-4">
        @foreach (var item in Model)
        {
            <div class="col-6 col-md-3 pt-3 px-1 px-md-2">
                <div class="card h-100">
                    <img src="@("data:image/*;base64,"+Convert.ToBase64String(item.Service.Image))" class="card-img-top" alt="Image 2" style="height: 220px;">
                    <div class="card-body bg-black border border-1 border-top-0 d-flex flex-column">
                        <div class="d-flex justify-content-between">
                            <div class="">
                                <h5 class="card-title cut">@item.Service.Name</h5>
                            </div>
                            <div class="price color">@item.Service.Price$</div>
                        </div>
                        <p class="card-text flex-grow-1">
                            @item.Service.Description
                        </p>
                        <div class="text-center">
                            <a asp-controller="CutFli" asp-action="Appointments" asp-route-service="@item.Service.Id">
                                <button class="px-lg-5  btn bookthis">
                                    Book
                                </button>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        }
    </div>
</div>
    <script src="~/js/Booking.js" ></script>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
    }